### ISSUE TITLE
Rather include a hosted version of the openlayers API

### ISSUE THREAD

**Issue by marcauberer** [StudentsAgainstCovid19/corona-aid#4]
I would recommend you to remove the downloaded code of the openlayers API from the project and switch to a hosted version of it.

Having a downloaded version has following disadvantages:
- It unnecessarily blows up the repo size
- You are unable to keep track of your code quality, since it's not quite good at the moment ([see here](https://app.codacy.com/gh/StudentsAgainstCovid19/corona-aid/dashboard)). I think this is also the fault of the openlayers library
- The repo uses a lot of unused code, which is not very clear to understand
- Slow git response time due to the large amount of files

**Comment by kellerfisch** [comment]
I just pushed in order to have a first working solution. I will change the whole map anyways. Give me some time.
