### ISSUE TITLE
Also reset rotation

### ISSUE THREAD

**Issue by marcauberer** [StudentsAgainstCovid19/corona-aid#49]
It's a small feature, but it would be nice to have also a reset functionality for the map rotation (on tablets for instance). We could combine this with the reset zoom feature.

**Comment by kellerfisch** [comment]
Why not prevent rotation? Rotation is neither a feature with use nor will it help making use of the map.

**Comment by marcauberer** [comment]
Ok. Then let's prevent rotation. I'm also fine with that.

**Comment by kellerfisch** [comment]
Did that. Testing, however, is quite difficult for me. Please test when branch is merged.

**Comment by kellerfisch** [comment]
Works.
