### ISSUE TITLE
SSL Certificate not working for production site

### ISSUE THREAD

**Issue by marcauberer** [StudentsAgainstCovid19/corona-aid#5]
The ssl certificate for the [sac19.jatsqi.com](https://sac19.jatsqi.com) website is not valid. The certificate is issued for [dbgui.jatsqi.com](https://dbgui.jatsqi.com). I don't know exacly what's the matter though.

**Comment by jatsqi** [comment]
The certificate itself is valid, but some parts of the website are not tranfered over https.
I dont know the exact reason, but I think that OpenLayers requests some of the data via http which causes this issue.

**Comment by marcauberer** [comment]
@keksklauer4 can we fix that?

**Comment by marcauberer** [comment]
Issue solved. Closing this.
