### ISSUE TITLE
Automatic Locking does not close every open pop-up

### ISSUE THREAD

**Issue by Splines** [StudentsAgainstCovid19/corona-aid#51]
When the user opens the symptoms pop-up and waits long enough, the pop-up "Ihre Session läuft ab. Wollen Sie weiterhin den Patienten bearbeiten?" opens up. If the user waits even longer the detail view will close but the symptoms pop-up stays open. The expected behaviour is that the detail view can't close automatically when the user has a open pop-up OR that every pop-up closes automatically together with the detail view.
Right now the symptom pop-up stays open and leads to an error message when clicking on the "Bestätigen" (submit) button.

![image](https://user-images.githubusercontent.com/37160523/86514008-ffe15b00-be0e-11ea-9e87-b9ddc79f165a.png)

**Comment by kellerfisch** [comment]
Cannot reproduce this bug. Tell me more about it.

**Comment by Splines** [comment]
I merged the new commits of develop into my branch and it works as expected now. I can't reproduce the issue anymore ;)
