### ISSUE TITLE
Focus on expiration pop-up

### ISSUE THREAD

**Issue by Splines** [StudentsAgainstCovid19/corona-aid#52]
The "expiration pop-up" can open up at all times, even if the user has another pop-up opened (see picture below). In this case, it should be clear that the "expiration pop-up" has the highest priority. That's why we should darken the rest of the screen. This way, the user doesn't click on the previously opened pop-up and wonders why the buttons are not working.

![image](https://user-images.githubusercontent.com/37160523/86514047-49ca4100-be0f-11ea-8056-a7afefd6c53e.png)

**Comment by kellerfisch** [comment]
I will take care of that.

**Comment by kellerfisch** [comment]
Done. I added an optional blur filter for the generic confirm popups. Branch will soon be merged.
