### ISSUE TITLE
Coherent use of tag names (reference)

### ISSUE THREAD

**Issue by Splines** [StudentsAgainstCovid19/corona-aid#53]
Please make sure you look at the following "backend"-issue, as this also affects the processing of the backend data in the frontend.

https://github.com/StudentsAgainstCovid19/corona-aid-api/issues/105#issue-650904677

**Comment by marcauberer** [comment]
The issue does not originate in the backend, so I closed the issue there.

**Comment by kellerfisch** [comment]
Has to do with the fact that some functionality was implemented in the frontend before the backend was ready. We will take care of this when improving code. Issue will be open until fixed, obviously.

**Comment by kellerfisch** [comment]
Rejected due to the fact that I am simply too lazy to change that. Apart from that, I am scared of the potential for new bugs (quite risky stuff) if I change the whole naming.
