### ISSUE TITLE
Adjust Logo

### ISSUE THREAD

**Issue by Splines** [StudentsAgainstCovid19/corona-aid#56]
Right now the logo looks like this on the map:
![image](https://user-images.githubusercontent.com/37160523/86516376-57d48d80-be20-11ea-8c29-7650a08c4bba.png)

I guess it would be better to use the png image instead which only shows the logo without the lettering next to it.
You can download the png image of the "pure" logo [here on our Trello board](https://trello-attachments.s3.amazonaws.com/5eb5560fb0d10a049597a97f/5ee4f69242556c51403e4bd1/c4aefec296cc34d3b207001135ae679e/Only_Logo.png).
![Pure Logo preview](https://trello-attachments.s3.amazonaws.com/5eb5560fb0d10a049597a97f/5ee4f69242556c51403e4bd1/c4aefec296cc34d3b207001135ae679e/Only_Logo.png)

**Comment by marcauberer** [comment]
Please wait with fixing that, till the open pr is merged. Otherwise we'll have merge conflicts.

**Comment by kellerfisch** [comment]
I appreciate the idea of having a PNG file but I would prefer the name of this project to be included somewhere apart from the url. Let's stick with the current design but change the file format.

**Comment by andirh** [comment]
I'm with Julien, I prefer the logo with the name of the project. I will change it as soon as possible.

**Comment by kellerfisch** [comment]
Done.
