### ISSUE TITLE
Map shows multiple clustered points for the same people

### ISSUE THREAD

**Issue by Splines** [StudentsAgainstCovid19/corona-aid#57]
The map sometimes shows several "cluster points" next to each other which refer to the same people. These points should be merged into one. This only concerns points next to each other which display the same number.

![image](https://user-images.githubusercontent.com/37160523/86516592-31175680-be22-11ea-82d6-969a2186b6a0.png)

**Comment by kellerfisch** [comment]
Confirmed as a bug. I will work on that.

**Comment by kellerfisch** [comment]
Did that. Turned out I forget validating a solution for a fixed bug last time. Thank you for noticing.
