### ISSUE TITLE
No pie charts in "clustered points"

### ISSUE THREAD

**Issue by Splines** [StudentsAgainstCovid19/corona-aid#58]
The "clustered points" don't reflect the current status you see in the clustered view (right sidebar when you click on a "clustered point". I thought we wanted to show information like "2 people processed, 8 more people to go" in the form of a pie chart.

![image](https://user-images.githubusercontent.com/37160523/86516650-bdc21480-be22-11ea-9ddd-d082e7ca057b.png)

**Comment by kellerfisch** [comment]
We decided on an indication for how many people remain. The number within the pie chart indicates the absolute amount of remaining people to call (not successfully called included).Therefore, there is no reason to change that, specifically taking into account that the status will make the pie charts confusing to the worker.

Currently, the pie charts display the proportion of people remaining in yellow, the proportion of people successfully called in green and the proportion of people with a missed called (and not successfully called yet). If you are wondering why everything is yellow, you probably did not change a person this day. To do so, you might want to run prepareData() in the console once (!) to at least see valid example data. Then wait for the update process to update or refresh the page. Note that realtime currently sometimes has issues with 503, therefore refreshing might be preferable.

**Comment by Splines** [comment]
@keksklauer4 Thank's for the clarification. I did indeed wonder why all the "clustered points" were yellow, so I thought we might have got rid of the pie chart. I will try it out with `prepareData()` now.

>  I thought we wanted to show information like "2 people processed, 8 more people to go" in the form of a pie chart.

With that statement, I didn't mean to show more labels inside of the pie chart. I just wanted to describe the pie chart I couldn't see on the screen.

I guess it would be advisable to introduce an automatation calling the `prepareData()` every midnight, so that Mr. Roethig sees more realistic examples no matter when he evaluates our project.

**Comment by marcauberer** [comment]
@Ordinateur-Hack I think it would be better to realize that behaviour in the backend. I'm opening an issue in the backend repo and closing this ;)
